[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'let g:vim_markdown_folding_disabled = 1'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'
